/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import models.PropertyModel;

/**
 *
 * @author Juan
 */
public class AddPropertyView extends javax.swing.JFrame {

    /**
     * Creates new form AddPropertyView
     */
    public AddPropertyView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgregarProperty = new javax.swing.JButton();
        priceProperty = new javax.swing.JTextField();
        descriptionProperty = new javax.swing.JTextField();
        sizeProperty = new javax.swing.JTextField();
        locationProperty = new javax.swing.JTextField();
        ownerProperty = new javax.swing.JTextField();
        isSaleProperty = new javax.swing.JCheckBox();
        inRentalProperty = new javax.swing.JCheckBox();
        typeProperty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarProperty.setText("Agregar");
        AgregarProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPropertyActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        priceProperty.setText("Precio");
        jPanel1.add(priceProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        descriptionProperty.setText("descripcion");
        jPanel1.add(descriptionProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        sizeProperty.setText("Tamaño");
        jPanel1.add(sizeProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        locationProperty.setText("localidad");
        jPanel1.add(locationProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        ownerProperty.setText("Dueño");
        jPanel1.add(ownerProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        isSaleProperty.setText("En Venta");
        isSaleProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSalePropertyActionPerformed(evt);
            }
        });
        jPanel1.add(isSaleProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        inRentalProperty.setText("En Alquiler");
        jPanel1.add(inRentalProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        typeProperty.setText("Tipo");
        jPanel1.add(typeProperty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPropertyActionPerformed
        
        Double precio = Double.parseDouble(priceProperty.getText());
        String descripcion = descriptionProperty.getText();
        int tamaño = Integer.parseInt(sizeProperty.getText());
        String locacion = locationProperty.getText();
        boolean enRenta = inRentalProperty.isSelected();
        boolean enVenta = isSaleProperty.isSelected();
        String tipo = typeProperty.getText();
        String dueño = ownerProperty.getText();
             
        PropertyModel propiedadesAdd = new PropertyModel(precio, descripcion,
        tamaño, locacion,enRenta, enVenta, tipo, dueño);
    }//GEN-LAST:event_AgregarPropertyActionPerformed

    private void isSalePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSalePropertyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSalePropertyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProperty;
    private javax.swing.JTextField descriptionProperty;
    private javax.swing.JCheckBox inRentalProperty;
    private javax.swing.JCheckBox isSaleProperty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationProperty;
    private javax.swing.JTextField ownerProperty;
    private javax.swing.JTextField priceProperty;
    private javax.swing.JTextField sizeProperty;
    private javax.swing.JTextField typeProperty;
    // End of variables declaration//GEN-END:variables

}
